version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: trackit_db
      PG_USER: postgres
      PG_PASSWORD: admin
      DATABASE_URL: ${PG_HOST}://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB}
    ports:
      - '5432:5432'
    networks:
      - app-network

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: trackit_db
      PG_USER: postgres
      PG_PASSWORD: admin
      DATABASE_URL: ${PG_HOST}://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB}
      PORT: 5000
      JWT_SECRET: b2e81469-1f71-481d-bc7e-9c5424b0f9d6
      CRYPTO_SECRET: d3e6fe80-d1ed-44d8-8e17-416a1b7271ef
      CRYPTO_IV_SECRET: 4b8e0933-a7f1-4545-8444-5276efecc9a8
      CRYPTO_ALGORITHM: AES-256-CBC
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
